version: '3.5'

services:

  ravendb:
    container_name: marketplace-ch8-ravendb
    image: ravendb/ravendb
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
